name: Conditions
on: [push] # triggers
jobs:
  hello:
    runs-on: ubuntu-latest # Linux OS. We can have windows or MAC
    steps: # stages
      - name: step1
        if: github.ref == 'refs/heads/feature-**' # If you want to perform some action in some
        run: echo "Hello World"                   # particular branch
      - name: step2
        if: github.ref == 'refs/heads/main'
        run: echo "Hello GitHub Actions"